package vfh.httpInterface.dao.buildings;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import vfh.httpInterface.model.BuildingsHouseType;
import vfh.httpInterface.model.BuildingsHouseTypeExample;

public interface BuildingsHouseTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_house_type
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    int countByExample(BuildingsHouseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_house_type
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    int deleteByExample(BuildingsHouseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_house_type
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_house_type
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    int insert(BuildingsHouseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_house_type
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    int insertSelective(BuildingsHouseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_house_type
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    List<BuildingsHouseType> selectByExample(BuildingsHouseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_house_type
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    BuildingsHouseType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_house_type
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") BuildingsHouseType record, @Param("example") BuildingsHouseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_house_type
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    int updateByExample(@Param("record") BuildingsHouseType record, @Param("example") BuildingsHouseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_house_type
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    int updateByPrimaryKeySelective(BuildingsHouseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_house_type
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    int updateByPrimaryKey(BuildingsHouseType record);
}