package vfh.httpInterface.dao.buildings;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import vfh.httpInterface.model.BuildingKeyValue;
import vfh.httpInterface.model.BuildingKeyValueExample;

public interface BuildingKeyValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_key_value
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    int countByExample(BuildingKeyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_key_value
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    int deleteByExample(BuildingKeyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_key_value
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_key_value
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    int insert(BuildingKeyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_key_value
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    int insertSelective(BuildingKeyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_key_value
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    List<BuildingKeyValue> selectByExample(BuildingKeyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_key_value
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    BuildingKeyValue selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_key_value
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    int updateByExampleSelective(@Param("record") BuildingKeyValue record, @Param("example") BuildingKeyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_key_value
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    int updateByExample(@Param("record") BuildingKeyValue record, @Param("example") BuildingKeyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_key_value
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    int updateByPrimaryKeySelective(BuildingKeyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_key_value
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    int updateByPrimaryKey(BuildingKeyValue record);
}