package vfh.httpInterface.dao.buildings;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import vfh.httpInterface.model.BuildingCompany;
import vfh.httpInterface.model.BuildingCompanyExample;

public interface BuildingCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_company
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    int countByExample(BuildingCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_company
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    int deleteByExample(BuildingCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_company
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    int insert(BuildingCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_company
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    int insertSelective(BuildingCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_company
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    List<BuildingCompany> selectByExample(BuildingCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_company
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") BuildingCompany record, @Param("example") BuildingCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_company
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    int updateByExample(@Param("record") BuildingCompany record, @Param("example") BuildingCompanyExample example);
}