package vfh.httpInterface.dao.buildings;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import vfh.httpInterface.model.Buildings;
import vfh.httpInterface.model.BuildingsExample;

public interface BuildingsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    int countByExample(BuildingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    int deleteByExample(BuildingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    int insert(Buildings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    int insertSelective(Buildings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    List<Buildings> selectByExample(BuildingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    Buildings selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    int updateByExampleSelective(@Param("record") Buildings record, @Param("example") BuildingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    int updateByExample(@Param("record") Buildings record, @Param("example") BuildingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    int updateByPrimaryKeySelective(Buildings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    int updateByPrimaryKey(Buildings record);
}