package vfh.httpInterface.dao.buildings;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import vfh.httpInterface.model.BuildingsPrice;
import vfh.httpInterface.model.BuildingsPriceExample;

public interface BuildingsPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_price
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    int countByExample(BuildingsPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_price
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    int deleteByExample(BuildingsPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_price
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_price
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    int insert(BuildingsPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_price
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    int insertSelective(BuildingsPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_price
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    List<BuildingsPrice> selectByExample(BuildingsPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_price
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    BuildingsPrice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_price
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    int updateByExampleSelective(@Param("record") BuildingsPrice record, @Param("example") BuildingsPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_price
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    int updateByExample(@Param("record") BuildingsPrice record, @Param("example") BuildingsPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_price
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    int updateByPrimaryKeySelective(BuildingsPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_price
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    int updateByPrimaryKey(BuildingsPrice record);
}