package vfh.httpInterface.dao.buildings;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import vfh.httpInterface.model.BuildingArea;
import vfh.httpInterface.model.BuildingAreaExample;

public interface BuildingAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    int countByExample(BuildingAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    int deleteByExample(BuildingAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    int insert(BuildingArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    int insertSelective(BuildingArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    List<BuildingArea> selectByExample(BuildingAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    int updateByExampleSelective(@Param("record") BuildingArea record, @Param("example") BuildingAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    int updateByExample(@Param("record") BuildingArea record, @Param("example") BuildingAreaExample example);
}