package vfh.httpInterface.dao.buildings;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import vfh.httpInterface.model.BuildingActive;
import vfh.httpInterface.model.BuildingActiveExample;

public interface BuildingActiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_active
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    int countByExample(BuildingActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_active
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    int deleteByExample(BuildingActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_active
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_active
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    int insert(BuildingActive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_active
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    int insertSelective(BuildingActive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_active
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    List<BuildingActive> selectByExampleWithBLOBs(BuildingActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_active
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    List<BuildingActive> selectByExample(BuildingActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_active
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    BuildingActive selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_active
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    int updateByExampleSelective(@Param("record") BuildingActive record, @Param("example") BuildingActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_active
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") BuildingActive record, @Param("example") BuildingActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_active
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    int updateByExample(@Param("record") BuildingActive record, @Param("example") BuildingActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_active
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    int updateByPrimaryKeySelective(BuildingActive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_active
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(BuildingActive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_active
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    int updateByPrimaryKey(BuildingActive record);
}