package vfh.httpInterface.model;

import java.util.ArrayList;
import java.util.List;

public class BuildingAreaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public BuildingAreaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAreaIdIsNull() {
            addCriterion("AREA_ID is null");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNotNull() {
            addCriterion("AREA_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAreaIdEqualTo(String value) {
            addCriterion("AREA_ID =", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotEqualTo(String value) {
            addCriterion("AREA_ID <>", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThan(String value) {
            addCriterion("AREA_ID >", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThanOrEqualTo(String value) {
            addCriterion("AREA_ID >=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThan(String value) {
            addCriterion("AREA_ID <", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThanOrEqualTo(String value) {
            addCriterion("AREA_ID <=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLike(String value) {
            addCriterion("AREA_ID like", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotLike(String value) {
            addCriterion("AREA_ID not like", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIn(List<String> values) {
            addCriterion("AREA_ID in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotIn(List<String> values) {
            addCriterion("AREA_ID not in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdBetween(String value1, String value2) {
            addCriterion("AREA_ID between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotBetween(String value1, String value2) {
            addCriterion("AREA_ID not between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaNameIsNull() {
            addCriterion("AREA_NAME is null");
            return (Criteria) this;
        }

        public Criteria andAreaNameIsNotNull() {
            addCriterion("AREA_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andAreaNameEqualTo(String value) {
            addCriterion("AREA_NAME =", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameNotEqualTo(String value) {
            addCriterion("AREA_NAME <>", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameGreaterThan(String value) {
            addCriterion("AREA_NAME >", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameGreaterThanOrEqualTo(String value) {
            addCriterion("AREA_NAME >=", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameLessThan(String value) {
            addCriterion("AREA_NAME <", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameLessThanOrEqualTo(String value) {
            addCriterion("AREA_NAME <=", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameLike(String value) {
            addCriterion("AREA_NAME like", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameNotLike(String value) {
            addCriterion("AREA_NAME not like", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameIn(List<String> values) {
            addCriterion("AREA_NAME in", values, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameNotIn(List<String> values) {
            addCriterion("AREA_NAME not in", values, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameBetween(String value1, String value2) {
            addCriterion("AREA_NAME between", value1, value2, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameNotBetween(String value1, String value2) {
            addCriterion("AREA_NAME not between", value1, value2, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaAliaIsNull() {
            addCriterion("AREA_ALIA is null");
            return (Criteria) this;
        }

        public Criteria andAreaAliaIsNotNull() {
            addCriterion("AREA_ALIA is not null");
            return (Criteria) this;
        }

        public Criteria andAreaAliaEqualTo(String value) {
            addCriterion("AREA_ALIA =", value, "areaAlia");
            return (Criteria) this;
        }

        public Criteria andAreaAliaNotEqualTo(String value) {
            addCriterion("AREA_ALIA <>", value, "areaAlia");
            return (Criteria) this;
        }

        public Criteria andAreaAliaGreaterThan(String value) {
            addCriterion("AREA_ALIA >", value, "areaAlia");
            return (Criteria) this;
        }

        public Criteria andAreaAliaGreaterThanOrEqualTo(String value) {
            addCriterion("AREA_ALIA >=", value, "areaAlia");
            return (Criteria) this;
        }

        public Criteria andAreaAliaLessThan(String value) {
            addCriterion("AREA_ALIA <", value, "areaAlia");
            return (Criteria) this;
        }

        public Criteria andAreaAliaLessThanOrEqualTo(String value) {
            addCriterion("AREA_ALIA <=", value, "areaAlia");
            return (Criteria) this;
        }

        public Criteria andAreaAliaLike(String value) {
            addCriterion("AREA_ALIA like", value, "areaAlia");
            return (Criteria) this;
        }

        public Criteria andAreaAliaNotLike(String value) {
            addCriterion("AREA_ALIA not like", value, "areaAlia");
            return (Criteria) this;
        }

        public Criteria andAreaAliaIn(List<String> values) {
            addCriterion("AREA_ALIA in", values, "areaAlia");
            return (Criteria) this;
        }

        public Criteria andAreaAliaNotIn(List<String> values) {
            addCriterion("AREA_ALIA not in", values, "areaAlia");
            return (Criteria) this;
        }

        public Criteria andAreaAliaBetween(String value1, String value2) {
            addCriterion("AREA_ALIA between", value1, value2, "areaAlia");
            return (Criteria) this;
        }

        public Criteria andAreaAliaNotBetween(String value1, String value2) {
            addCriterion("AREA_ALIA not between", value1, value2, "areaAlia");
            return (Criteria) this;
        }

        public Criteria andParentAreaIdIsNull() {
            addCriterion("PARENT_AREA_ID is null");
            return (Criteria) this;
        }

        public Criteria andParentAreaIdIsNotNull() {
            addCriterion("PARENT_AREA_ID is not null");
            return (Criteria) this;
        }

        public Criteria andParentAreaIdEqualTo(String value) {
            addCriterion("PARENT_AREA_ID =", value, "parentAreaId");
            return (Criteria) this;
        }

        public Criteria andParentAreaIdNotEqualTo(String value) {
            addCriterion("PARENT_AREA_ID <>", value, "parentAreaId");
            return (Criteria) this;
        }

        public Criteria andParentAreaIdGreaterThan(String value) {
            addCriterion("PARENT_AREA_ID >", value, "parentAreaId");
            return (Criteria) this;
        }

        public Criteria andParentAreaIdGreaterThanOrEqualTo(String value) {
            addCriterion("PARENT_AREA_ID >=", value, "parentAreaId");
            return (Criteria) this;
        }

        public Criteria andParentAreaIdLessThan(String value) {
            addCriterion("PARENT_AREA_ID <", value, "parentAreaId");
            return (Criteria) this;
        }

        public Criteria andParentAreaIdLessThanOrEqualTo(String value) {
            addCriterion("PARENT_AREA_ID <=", value, "parentAreaId");
            return (Criteria) this;
        }

        public Criteria andParentAreaIdLike(String value) {
            addCriterion("PARENT_AREA_ID like", value, "parentAreaId");
            return (Criteria) this;
        }

        public Criteria andParentAreaIdNotLike(String value) {
            addCriterion("PARENT_AREA_ID not like", value, "parentAreaId");
            return (Criteria) this;
        }

        public Criteria andParentAreaIdIn(List<String> values) {
            addCriterion("PARENT_AREA_ID in", values, "parentAreaId");
            return (Criteria) this;
        }

        public Criteria andParentAreaIdNotIn(List<String> values) {
            addCriterion("PARENT_AREA_ID not in", values, "parentAreaId");
            return (Criteria) this;
        }

        public Criteria andParentAreaIdBetween(String value1, String value2) {
            addCriterion("PARENT_AREA_ID between", value1, value2, "parentAreaId");
            return (Criteria) this;
        }

        public Criteria andParentAreaIdNotBetween(String value1, String value2) {
            addCriterion("PARENT_AREA_ID not between", value1, value2, "parentAreaId");
            return (Criteria) this;
        }

        public Criteria andProIdIsNull() {
            addCriterion("PRO_ID is null");
            return (Criteria) this;
        }

        public Criteria andProIdIsNotNull() {
            addCriterion("PRO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProIdEqualTo(String value) {
            addCriterion("PRO_ID =", value, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdNotEqualTo(String value) {
            addCriterion("PRO_ID <>", value, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdGreaterThan(String value) {
            addCriterion("PRO_ID >", value, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdGreaterThanOrEqualTo(String value) {
            addCriterion("PRO_ID >=", value, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdLessThan(String value) {
            addCriterion("PRO_ID <", value, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdLessThanOrEqualTo(String value) {
            addCriterion("PRO_ID <=", value, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdLike(String value) {
            addCriterion("PRO_ID like", value, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdNotLike(String value) {
            addCriterion("PRO_ID not like", value, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdIn(List<String> values) {
            addCriterion("PRO_ID in", values, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdNotIn(List<String> values) {
            addCriterion("PRO_ID not in", values, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdBetween(String value1, String value2) {
            addCriterion("PRO_ID between", value1, value2, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdNotBetween(String value1, String value2) {
            addCriterion("PRO_ID not between", value1, value2, "proId");
            return (Criteria) this;
        }

        public Criteria andProNameIsNull() {
            addCriterion("PRO_NAME is null");
            return (Criteria) this;
        }

        public Criteria andProNameIsNotNull() {
            addCriterion("PRO_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andProNameEqualTo(String value) {
            addCriterion("PRO_NAME =", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameNotEqualTo(String value) {
            addCriterion("PRO_NAME <>", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameGreaterThan(String value) {
            addCriterion("PRO_NAME >", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameGreaterThanOrEqualTo(String value) {
            addCriterion("PRO_NAME >=", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameLessThan(String value) {
            addCriterion("PRO_NAME <", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameLessThanOrEqualTo(String value) {
            addCriterion("PRO_NAME <=", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameLike(String value) {
            addCriterion("PRO_NAME like", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameNotLike(String value) {
            addCriterion("PRO_NAME not like", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameIn(List<String> values) {
            addCriterion("PRO_NAME in", values, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameNotIn(List<String> values) {
            addCriterion("PRO_NAME not in", values, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameBetween(String value1, String value2) {
            addCriterion("PRO_NAME between", value1, value2, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameNotBetween(String value1, String value2) {
            addCriterion("PRO_NAME not between", value1, value2, "proName");
            return (Criteria) this;
        }

        public Criteria andProAliaIsNull() {
            addCriterion("PRO_ALIA is null");
            return (Criteria) this;
        }

        public Criteria andProAliaIsNotNull() {
            addCriterion("PRO_ALIA is not null");
            return (Criteria) this;
        }

        public Criteria andProAliaEqualTo(String value) {
            addCriterion("PRO_ALIA =", value, "proAlia");
            return (Criteria) this;
        }

        public Criteria andProAliaNotEqualTo(String value) {
            addCriterion("PRO_ALIA <>", value, "proAlia");
            return (Criteria) this;
        }

        public Criteria andProAliaGreaterThan(String value) {
            addCriterion("PRO_ALIA >", value, "proAlia");
            return (Criteria) this;
        }

        public Criteria andProAliaGreaterThanOrEqualTo(String value) {
            addCriterion("PRO_ALIA >=", value, "proAlia");
            return (Criteria) this;
        }

        public Criteria andProAliaLessThan(String value) {
            addCriterion("PRO_ALIA <", value, "proAlia");
            return (Criteria) this;
        }

        public Criteria andProAliaLessThanOrEqualTo(String value) {
            addCriterion("PRO_ALIA <=", value, "proAlia");
            return (Criteria) this;
        }

        public Criteria andProAliaLike(String value) {
            addCriterion("PRO_ALIA like", value, "proAlia");
            return (Criteria) this;
        }

        public Criteria andProAliaNotLike(String value) {
            addCriterion("PRO_ALIA not like", value, "proAlia");
            return (Criteria) this;
        }

        public Criteria andProAliaIn(List<String> values) {
            addCriterion("PRO_ALIA in", values, "proAlia");
            return (Criteria) this;
        }

        public Criteria andProAliaNotIn(List<String> values) {
            addCriterion("PRO_ALIA not in", values, "proAlia");
            return (Criteria) this;
        }

        public Criteria andProAliaBetween(String value1, String value2) {
            addCriterion("PRO_ALIA between", value1, value2, "proAlia");
            return (Criteria) this;
        }

        public Criteria andProAliaNotBetween(String value1, String value2) {
            addCriterion("PRO_ALIA not between", value1, value2, "proAlia");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNull() {
            addCriterion("CITY_ID is null");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNotNull() {
            addCriterion("CITY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCityIdEqualTo(String value) {
            addCriterion("CITY_ID =", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotEqualTo(String value) {
            addCriterion("CITY_ID <>", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThan(String value) {
            addCriterion("CITY_ID >", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThanOrEqualTo(String value) {
            addCriterion("CITY_ID >=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThan(String value) {
            addCriterion("CITY_ID <", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThanOrEqualTo(String value) {
            addCriterion("CITY_ID <=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLike(String value) {
            addCriterion("CITY_ID like", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotLike(String value) {
            addCriterion("CITY_ID not like", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdIn(List<String> values) {
            addCriterion("CITY_ID in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotIn(List<String> values) {
            addCriterion("CITY_ID not in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdBetween(String value1, String value2) {
            addCriterion("CITY_ID between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotBetween(String value1, String value2) {
            addCriterion("CITY_ID not between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityNameIsNull() {
            addCriterion("CITY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCityNameIsNotNull() {
            addCriterion("CITY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCityNameEqualTo(String value) {
            addCriterion("CITY_NAME =", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotEqualTo(String value) {
            addCriterion("CITY_NAME <>", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameGreaterThan(String value) {
            addCriterion("CITY_NAME >", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameGreaterThanOrEqualTo(String value) {
            addCriterion("CITY_NAME >=", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLessThan(String value) {
            addCriterion("CITY_NAME <", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLessThanOrEqualTo(String value) {
            addCriterion("CITY_NAME <=", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLike(String value) {
            addCriterion("CITY_NAME like", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotLike(String value) {
            addCriterion("CITY_NAME not like", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameIn(List<String> values) {
            addCriterion("CITY_NAME in", values, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotIn(List<String> values) {
            addCriterion("CITY_NAME not in", values, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameBetween(String value1, String value2) {
            addCriterion("CITY_NAME between", value1, value2, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotBetween(String value1, String value2) {
            addCriterion("CITY_NAME not between", value1, value2, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityAliaIsNull() {
            addCriterion("CITY_ALIA is null");
            return (Criteria) this;
        }

        public Criteria andCityAliaIsNotNull() {
            addCriterion("CITY_ALIA is not null");
            return (Criteria) this;
        }

        public Criteria andCityAliaEqualTo(String value) {
            addCriterion("CITY_ALIA =", value, "cityAlia");
            return (Criteria) this;
        }

        public Criteria andCityAliaNotEqualTo(String value) {
            addCriterion("CITY_ALIA <>", value, "cityAlia");
            return (Criteria) this;
        }

        public Criteria andCityAliaGreaterThan(String value) {
            addCriterion("CITY_ALIA >", value, "cityAlia");
            return (Criteria) this;
        }

        public Criteria andCityAliaGreaterThanOrEqualTo(String value) {
            addCriterion("CITY_ALIA >=", value, "cityAlia");
            return (Criteria) this;
        }

        public Criteria andCityAliaLessThan(String value) {
            addCriterion("CITY_ALIA <", value, "cityAlia");
            return (Criteria) this;
        }

        public Criteria andCityAliaLessThanOrEqualTo(String value) {
            addCriterion("CITY_ALIA <=", value, "cityAlia");
            return (Criteria) this;
        }

        public Criteria andCityAliaLike(String value) {
            addCriterion("CITY_ALIA like", value, "cityAlia");
            return (Criteria) this;
        }

        public Criteria andCityAliaNotLike(String value) {
            addCriterion("CITY_ALIA not like", value, "cityAlia");
            return (Criteria) this;
        }

        public Criteria andCityAliaIn(List<String> values) {
            addCriterion("CITY_ALIA in", values, "cityAlia");
            return (Criteria) this;
        }

        public Criteria andCityAliaNotIn(List<String> values) {
            addCriterion("CITY_ALIA not in", values, "cityAlia");
            return (Criteria) this;
        }

        public Criteria andCityAliaBetween(String value1, String value2) {
            addCriterion("CITY_ALIA between", value1, value2, "cityAlia");
            return (Criteria) this;
        }

        public Criteria andCityAliaNotBetween(String value1, String value2) {
            addCriterion("CITY_ALIA not between", value1, value2, "cityAlia");
            return (Criteria) this;
        }

        public Criteria andAreaLevelIsNull() {
            addCriterion("AREA_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andAreaLevelIsNotNull() {
            addCriterion("AREA_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andAreaLevelEqualTo(String value) {
            addCriterion("AREA_LEVEL =", value, "areaLevel");
            return (Criteria) this;
        }

        public Criteria andAreaLevelNotEqualTo(String value) {
            addCriterion("AREA_LEVEL <>", value, "areaLevel");
            return (Criteria) this;
        }

        public Criteria andAreaLevelGreaterThan(String value) {
            addCriterion("AREA_LEVEL >", value, "areaLevel");
            return (Criteria) this;
        }

        public Criteria andAreaLevelGreaterThanOrEqualTo(String value) {
            addCriterion("AREA_LEVEL >=", value, "areaLevel");
            return (Criteria) this;
        }

        public Criteria andAreaLevelLessThan(String value) {
            addCriterion("AREA_LEVEL <", value, "areaLevel");
            return (Criteria) this;
        }

        public Criteria andAreaLevelLessThanOrEqualTo(String value) {
            addCriterion("AREA_LEVEL <=", value, "areaLevel");
            return (Criteria) this;
        }

        public Criteria andAreaLevelLike(String value) {
            addCriterion("AREA_LEVEL like", value, "areaLevel");
            return (Criteria) this;
        }

        public Criteria andAreaLevelNotLike(String value) {
            addCriterion("AREA_LEVEL not like", value, "areaLevel");
            return (Criteria) this;
        }

        public Criteria andAreaLevelIn(List<String> values) {
            addCriterion("AREA_LEVEL in", values, "areaLevel");
            return (Criteria) this;
        }

        public Criteria andAreaLevelNotIn(List<String> values) {
            addCriterion("AREA_LEVEL not in", values, "areaLevel");
            return (Criteria) this;
        }

        public Criteria andAreaLevelBetween(String value1, String value2) {
            addCriterion("AREA_LEVEL between", value1, value2, "areaLevel");
            return (Criteria) this;
        }

        public Criteria andAreaLevelNotBetween(String value1, String value2) {
            addCriterion("AREA_LEVEL not between", value1, value2, "areaLevel");
            return (Criteria) this;
        }

        public Criteria andPostCodeIsNull() {
            addCriterion("POST_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPostCodeIsNotNull() {
            addCriterion("POST_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPostCodeEqualTo(String value) {
            addCriterion("POST_CODE =", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeNotEqualTo(String value) {
            addCriterion("POST_CODE <>", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeGreaterThan(String value) {
            addCriterion("POST_CODE >", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeGreaterThanOrEqualTo(String value) {
            addCriterion("POST_CODE >=", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeLessThan(String value) {
            addCriterion("POST_CODE <", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeLessThanOrEqualTo(String value) {
            addCriterion("POST_CODE <=", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeLike(String value) {
            addCriterion("POST_CODE like", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeNotLike(String value) {
            addCriterion("POST_CODE not like", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeIn(List<String> values) {
            addCriterion("POST_CODE in", values, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeNotIn(List<String> values) {
            addCriterion("POST_CODE not in", values, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeBetween(String value1, String value2) {
            addCriterion("POST_CODE between", value1, value2, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeNotBetween(String value1, String value2) {
            addCriterion("POST_CODE not between", value1, value2, "postCode");
            return (Criteria) this;
        }

        public Criteria andTelAreaNoIsNull() {
            addCriterion("TEL_AREA_NO is null");
            return (Criteria) this;
        }

        public Criteria andTelAreaNoIsNotNull() {
            addCriterion("TEL_AREA_NO is not null");
            return (Criteria) this;
        }

        public Criteria andTelAreaNoEqualTo(String value) {
            addCriterion("TEL_AREA_NO =", value, "telAreaNo");
            return (Criteria) this;
        }

        public Criteria andTelAreaNoNotEqualTo(String value) {
            addCriterion("TEL_AREA_NO <>", value, "telAreaNo");
            return (Criteria) this;
        }

        public Criteria andTelAreaNoGreaterThan(String value) {
            addCriterion("TEL_AREA_NO >", value, "telAreaNo");
            return (Criteria) this;
        }

        public Criteria andTelAreaNoGreaterThanOrEqualTo(String value) {
            addCriterion("TEL_AREA_NO >=", value, "telAreaNo");
            return (Criteria) this;
        }

        public Criteria andTelAreaNoLessThan(String value) {
            addCriterion("TEL_AREA_NO <", value, "telAreaNo");
            return (Criteria) this;
        }

        public Criteria andTelAreaNoLessThanOrEqualTo(String value) {
            addCriterion("TEL_AREA_NO <=", value, "telAreaNo");
            return (Criteria) this;
        }

        public Criteria andTelAreaNoLike(String value) {
            addCriterion("TEL_AREA_NO like", value, "telAreaNo");
            return (Criteria) this;
        }

        public Criteria andTelAreaNoNotLike(String value) {
            addCriterion("TEL_AREA_NO not like", value, "telAreaNo");
            return (Criteria) this;
        }

        public Criteria andTelAreaNoIn(List<String> values) {
            addCriterion("TEL_AREA_NO in", values, "telAreaNo");
            return (Criteria) this;
        }

        public Criteria andTelAreaNoNotIn(List<String> values) {
            addCriterion("TEL_AREA_NO not in", values, "telAreaNo");
            return (Criteria) this;
        }

        public Criteria andTelAreaNoBetween(String value1, String value2) {
            addCriterion("TEL_AREA_NO between", value1, value2, "telAreaNo");
            return (Criteria) this;
        }

        public Criteria andTelAreaNoNotBetween(String value1, String value2) {
            addCriterion("TEL_AREA_NO not between", value1, value2, "telAreaNo");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("AREA is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("AREA is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("AREA =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("AREA <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("AREA >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("AREA >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("AREA <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("AREA <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("AREA like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("AREA not like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<String> values) {
            addCriterion("AREA in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<String> values) {
            addCriterion("AREA not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("AREA between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("AREA not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("ORDER_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("ORDER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("ORDER_ID =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("ORDER_ID <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("ORDER_ID >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_ID >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("ORDER_ID <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("ORDER_ID <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("ORDER_ID like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("ORDER_ID not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("ORDER_ID in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("ORDER_ID not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("ORDER_ID between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("ORDER_ID not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("LATITUDE is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("LATITUDE is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(String value) {
            addCriterion("LATITUDE =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(String value) {
            addCriterion("LATITUDE <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(String value) {
            addCriterion("LATITUDE >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(String value) {
            addCriterion("LATITUDE >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(String value) {
            addCriterion("LATITUDE <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(String value) {
            addCriterion("LATITUDE <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLike(String value) {
            addCriterion("LATITUDE like", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotLike(String value) {
            addCriterion("LATITUDE not like", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<String> values) {
            addCriterion("LATITUDE in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<String> values) {
            addCriterion("LATITUDE not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(String value1, String value2) {
            addCriterion("LATITUDE between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(String value1, String value2) {
            addCriterion("LATITUDE not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("LONGITUDE is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("LONGITUDE is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(String value) {
            addCriterion("LONGITUDE =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(String value) {
            addCriterion("LONGITUDE <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(String value) {
            addCriterion("LONGITUDE >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(String value) {
            addCriterion("LONGITUDE >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(String value) {
            addCriterion("LONGITUDE <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(String value) {
            addCriterion("LONGITUDE <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLike(String value) {
            addCriterion("LONGITUDE like", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotLike(String value) {
            addCriterion("LONGITUDE not like", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<String> values) {
            addCriterion("LONGITUDE in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<String> values) {
            addCriterion("LONGITUDE not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(String value1, String value2) {
            addCriterion("LONGITUDE between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(String value1, String value2) {
            addCriterion("LONGITUDE not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andSpellIsNull() {
            addCriterion("SPELL is null");
            return (Criteria) this;
        }

        public Criteria andSpellIsNotNull() {
            addCriterion("SPELL is not null");
            return (Criteria) this;
        }

        public Criteria andSpellEqualTo(String value) {
            addCriterion("SPELL =", value, "spell");
            return (Criteria) this;
        }

        public Criteria andSpellNotEqualTo(String value) {
            addCriterion("SPELL <>", value, "spell");
            return (Criteria) this;
        }

        public Criteria andSpellGreaterThan(String value) {
            addCriterion("SPELL >", value, "spell");
            return (Criteria) this;
        }

        public Criteria andSpellGreaterThanOrEqualTo(String value) {
            addCriterion("SPELL >=", value, "spell");
            return (Criteria) this;
        }

        public Criteria andSpellLessThan(String value) {
            addCriterion("SPELL <", value, "spell");
            return (Criteria) this;
        }

        public Criteria andSpellLessThanOrEqualTo(String value) {
            addCriterion("SPELL <=", value, "spell");
            return (Criteria) this;
        }

        public Criteria andSpellLike(String value) {
            addCriterion("SPELL like", value, "spell");
            return (Criteria) this;
        }

        public Criteria andSpellNotLike(String value) {
            addCriterion("SPELL not like", value, "spell");
            return (Criteria) this;
        }

        public Criteria andSpellIn(List<String> values) {
            addCriterion("SPELL in", values, "spell");
            return (Criteria) this;
        }

        public Criteria andSpellNotIn(List<String> values) {
            addCriterion("SPELL not in", values, "spell");
            return (Criteria) this;
        }

        public Criteria andSpellBetween(String value1, String value2) {
            addCriterion("SPELL between", value1, value2, "spell");
            return (Criteria) this;
        }

        public Criteria andSpellNotBetween(String value1, String value2) {
            addCriterion("SPELL not between", value1, value2, "spell");
            return (Criteria) this;
        }

        public Criteria andShortSpellIsNull() {
            addCriterion("SHORT_SPELL is null");
            return (Criteria) this;
        }

        public Criteria andShortSpellIsNotNull() {
            addCriterion("SHORT_SPELL is not null");
            return (Criteria) this;
        }

        public Criteria andShortSpellEqualTo(String value) {
            addCriterion("SHORT_SPELL =", value, "shortSpell");
            return (Criteria) this;
        }

        public Criteria andShortSpellNotEqualTo(String value) {
            addCriterion("SHORT_SPELL <>", value, "shortSpell");
            return (Criteria) this;
        }

        public Criteria andShortSpellGreaterThan(String value) {
            addCriterion("SHORT_SPELL >", value, "shortSpell");
            return (Criteria) this;
        }

        public Criteria andShortSpellGreaterThanOrEqualTo(String value) {
            addCriterion("SHORT_SPELL >=", value, "shortSpell");
            return (Criteria) this;
        }

        public Criteria andShortSpellLessThan(String value) {
            addCriterion("SHORT_SPELL <", value, "shortSpell");
            return (Criteria) this;
        }

        public Criteria andShortSpellLessThanOrEqualTo(String value) {
            addCriterion("SHORT_SPELL <=", value, "shortSpell");
            return (Criteria) this;
        }

        public Criteria andShortSpellLike(String value) {
            addCriterion("SHORT_SPELL like", value, "shortSpell");
            return (Criteria) this;
        }

        public Criteria andShortSpellNotLike(String value) {
            addCriterion("SHORT_SPELL not like", value, "shortSpell");
            return (Criteria) this;
        }

        public Criteria andShortSpellIn(List<String> values) {
            addCriterion("SHORT_SPELL in", values, "shortSpell");
            return (Criteria) this;
        }

        public Criteria andShortSpellNotIn(List<String> values) {
            addCriterion("SHORT_SPELL not in", values, "shortSpell");
            return (Criteria) this;
        }

        public Criteria andShortSpellBetween(String value1, String value2) {
            addCriterion("SHORT_SPELL between", value1, value2, "shortSpell");
            return (Criteria) this;
        }

        public Criteria andShortSpellNotBetween(String value1, String value2) {
            addCriterion("SHORT_SPELL not between", value1, value2, "shortSpell");
            return (Criteria) this;
        }

        public Criteria andAreaClusterIsNull() {
            addCriterion("AREA_CLUSTER is null");
            return (Criteria) this;
        }

        public Criteria andAreaClusterIsNotNull() {
            addCriterion("AREA_CLUSTER is not null");
            return (Criteria) this;
        }

        public Criteria andAreaClusterEqualTo(String value) {
            addCriterion("AREA_CLUSTER =", value, "areaCluster");
            return (Criteria) this;
        }

        public Criteria andAreaClusterNotEqualTo(String value) {
            addCriterion("AREA_CLUSTER <>", value, "areaCluster");
            return (Criteria) this;
        }

        public Criteria andAreaClusterGreaterThan(String value) {
            addCriterion("AREA_CLUSTER >", value, "areaCluster");
            return (Criteria) this;
        }

        public Criteria andAreaClusterGreaterThanOrEqualTo(String value) {
            addCriterion("AREA_CLUSTER >=", value, "areaCluster");
            return (Criteria) this;
        }

        public Criteria andAreaClusterLessThan(String value) {
            addCriterion("AREA_CLUSTER <", value, "areaCluster");
            return (Criteria) this;
        }

        public Criteria andAreaClusterLessThanOrEqualTo(String value) {
            addCriterion("AREA_CLUSTER <=", value, "areaCluster");
            return (Criteria) this;
        }

        public Criteria andAreaClusterLike(String value) {
            addCriterion("AREA_CLUSTER like", value, "areaCluster");
            return (Criteria) this;
        }

        public Criteria andAreaClusterNotLike(String value) {
            addCriterion("AREA_CLUSTER not like", value, "areaCluster");
            return (Criteria) this;
        }

        public Criteria andAreaClusterIn(List<String> values) {
            addCriterion("AREA_CLUSTER in", values, "areaCluster");
            return (Criteria) this;
        }

        public Criteria andAreaClusterNotIn(List<String> values) {
            addCriterion("AREA_CLUSTER not in", values, "areaCluster");
            return (Criteria) this;
        }

        public Criteria andAreaClusterBetween(String value1, String value2) {
            addCriterion("AREA_CLUSTER between", value1, value2, "areaCluster");
            return (Criteria) this;
        }

        public Criteria andAreaClusterNotBetween(String value1, String value2) {
            addCriterion("AREA_CLUSTER not between", value1, value2, "areaCluster");
            return (Criteria) this;
        }

        public Criteria andAppPreventIsNull() {
            addCriterion("APP_PREVENT is null");
            return (Criteria) this;
        }

        public Criteria andAppPreventIsNotNull() {
            addCriterion("APP_PREVENT is not null");
            return (Criteria) this;
        }

        public Criteria andAppPreventEqualTo(String value) {
            addCriterion("APP_PREVENT =", value, "appPrevent");
            return (Criteria) this;
        }

        public Criteria andAppPreventNotEqualTo(String value) {
            addCriterion("APP_PREVENT <>", value, "appPrevent");
            return (Criteria) this;
        }

        public Criteria andAppPreventGreaterThan(String value) {
            addCriterion("APP_PREVENT >", value, "appPrevent");
            return (Criteria) this;
        }

        public Criteria andAppPreventGreaterThanOrEqualTo(String value) {
            addCriterion("APP_PREVENT >=", value, "appPrevent");
            return (Criteria) this;
        }

        public Criteria andAppPreventLessThan(String value) {
            addCriterion("APP_PREVENT <", value, "appPrevent");
            return (Criteria) this;
        }

        public Criteria andAppPreventLessThanOrEqualTo(String value) {
            addCriterion("APP_PREVENT <=", value, "appPrevent");
            return (Criteria) this;
        }

        public Criteria andAppPreventLike(String value) {
            addCriterion("APP_PREVENT like", value, "appPrevent");
            return (Criteria) this;
        }

        public Criteria andAppPreventNotLike(String value) {
            addCriterion("APP_PREVENT not like", value, "appPrevent");
            return (Criteria) this;
        }

        public Criteria andAppPreventIn(List<String> values) {
            addCriterion("APP_PREVENT in", values, "appPrevent");
            return (Criteria) this;
        }

        public Criteria andAppPreventNotIn(List<String> values) {
            addCriterion("APP_PREVENT not in", values, "appPrevent");
            return (Criteria) this;
        }

        public Criteria andAppPreventBetween(String value1, String value2) {
            addCriterion("APP_PREVENT between", value1, value2, "appPrevent");
            return (Criteria) this;
        }

        public Criteria andAppPreventNotBetween(String value1, String value2) {
            addCriterion("APP_PREVENT not between", value1, value2, "appPrevent");
            return (Criteria) this;
        }

        public Criteria andSearchTypeIsNull() {
            addCriterion("SEARCH_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSearchTypeIsNotNull() {
            addCriterion("SEARCH_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSearchTypeEqualTo(String value) {
            addCriterion("SEARCH_TYPE =", value, "searchType");
            return (Criteria) this;
        }

        public Criteria andSearchTypeNotEqualTo(String value) {
            addCriterion("SEARCH_TYPE <>", value, "searchType");
            return (Criteria) this;
        }

        public Criteria andSearchTypeGreaterThan(String value) {
            addCriterion("SEARCH_TYPE >", value, "searchType");
            return (Criteria) this;
        }

        public Criteria andSearchTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SEARCH_TYPE >=", value, "searchType");
            return (Criteria) this;
        }

        public Criteria andSearchTypeLessThan(String value) {
            addCriterion("SEARCH_TYPE <", value, "searchType");
            return (Criteria) this;
        }

        public Criteria andSearchTypeLessThanOrEqualTo(String value) {
            addCriterion("SEARCH_TYPE <=", value, "searchType");
            return (Criteria) this;
        }

        public Criteria andSearchTypeLike(String value) {
            addCriterion("SEARCH_TYPE like", value, "searchType");
            return (Criteria) this;
        }

        public Criteria andSearchTypeNotLike(String value) {
            addCriterion("SEARCH_TYPE not like", value, "searchType");
            return (Criteria) this;
        }

        public Criteria andSearchTypeIn(List<String> values) {
            addCriterion("SEARCH_TYPE in", values, "searchType");
            return (Criteria) this;
        }

        public Criteria andSearchTypeNotIn(List<String> values) {
            addCriterion("SEARCH_TYPE not in", values, "searchType");
            return (Criteria) this;
        }

        public Criteria andSearchTypeBetween(String value1, String value2) {
            addCriterion("SEARCH_TYPE between", value1, value2, "searchType");
            return (Criteria) this;
        }

        public Criteria andSearchTypeNotBetween(String value1, String value2) {
            addCriterion("SEARCH_TYPE not between", value1, value2, "searchType");
            return (Criteria) this;
        }

        public Criteria andInstalledIsNull() {
            addCriterion("INSTALLED is null");
            return (Criteria) this;
        }

        public Criteria andInstalledIsNotNull() {
            addCriterion("INSTALLED is not null");
            return (Criteria) this;
        }

        public Criteria andInstalledEqualTo(Integer value) {
            addCriterion("INSTALLED =", value, "installed");
            return (Criteria) this;
        }

        public Criteria andInstalledNotEqualTo(Integer value) {
            addCriterion("INSTALLED <>", value, "installed");
            return (Criteria) this;
        }

        public Criteria andInstalledGreaterThan(Integer value) {
            addCriterion("INSTALLED >", value, "installed");
            return (Criteria) this;
        }

        public Criteria andInstalledGreaterThanOrEqualTo(Integer value) {
            addCriterion("INSTALLED >=", value, "installed");
            return (Criteria) this;
        }

        public Criteria andInstalledLessThan(Integer value) {
            addCriterion("INSTALLED <", value, "installed");
            return (Criteria) this;
        }

        public Criteria andInstalledLessThanOrEqualTo(Integer value) {
            addCriterion("INSTALLED <=", value, "installed");
            return (Criteria) this;
        }

        public Criteria andInstalledIn(List<Integer> values) {
            addCriterion("INSTALLED in", values, "installed");
            return (Criteria) this;
        }

        public Criteria andInstalledNotIn(List<Integer> values) {
            addCriterion("INSTALLED not in", values, "installed");
            return (Criteria) this;
        }

        public Criteria andInstalledBetween(Integer value1, Integer value2) {
            addCriterion("INSTALLED between", value1, value2, "installed");
            return (Criteria) this;
        }

        public Criteria andInstalledNotBetween(Integer value1, Integer value2) {
            addCriterion("INSTALLED not between", value1, value2, "installed");
            return (Criteria) this;
        }

        public Criteria andActivationIsNull() {
            addCriterion("ACTIVATION is null");
            return (Criteria) this;
        }

        public Criteria andActivationIsNotNull() {
            addCriterion("ACTIVATION is not null");
            return (Criteria) this;
        }

        public Criteria andActivationEqualTo(Integer value) {
            addCriterion("ACTIVATION =", value, "activation");
            return (Criteria) this;
        }

        public Criteria andActivationNotEqualTo(Integer value) {
            addCriterion("ACTIVATION <>", value, "activation");
            return (Criteria) this;
        }

        public Criteria andActivationGreaterThan(Integer value) {
            addCriterion("ACTIVATION >", value, "activation");
            return (Criteria) this;
        }

        public Criteria andActivationGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACTIVATION >=", value, "activation");
            return (Criteria) this;
        }

        public Criteria andActivationLessThan(Integer value) {
            addCriterion("ACTIVATION <", value, "activation");
            return (Criteria) this;
        }

        public Criteria andActivationLessThanOrEqualTo(Integer value) {
            addCriterion("ACTIVATION <=", value, "activation");
            return (Criteria) this;
        }

        public Criteria andActivationIn(List<Integer> values) {
            addCriterion("ACTIVATION in", values, "activation");
            return (Criteria) this;
        }

        public Criteria andActivationNotIn(List<Integer> values) {
            addCriterion("ACTIVATION not in", values, "activation");
            return (Criteria) this;
        }

        public Criteria andActivationBetween(Integer value1, Integer value2) {
            addCriterion("ACTIVATION between", value1, value2, "activation");
            return (Criteria) this;
        }

        public Criteria andActivationNotBetween(Integer value1, Integer value2) {
            addCriterion("ACTIVATION not between", value1, value2, "activation");
            return (Criteria) this;
        }

        public Criteria andActiveIsNull() {
            addCriterion("ACTIVE is null");
            return (Criteria) this;
        }

        public Criteria andActiveIsNotNull() {
            addCriterion("ACTIVE is not null");
            return (Criteria) this;
        }

        public Criteria andActiveEqualTo(Integer value) {
            addCriterion("ACTIVE =", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveNotEqualTo(Integer value) {
            addCriterion("ACTIVE <>", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveGreaterThan(Integer value) {
            addCriterion("ACTIVE >", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACTIVE >=", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveLessThan(Integer value) {
            addCriterion("ACTIVE <", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveLessThanOrEqualTo(Integer value) {
            addCriterion("ACTIVE <=", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveIn(List<Integer> values) {
            addCriterion("ACTIVE in", values, "active");
            return (Criteria) this;
        }

        public Criteria andActiveNotIn(List<Integer> values) {
            addCriterion("ACTIVE not in", values, "active");
            return (Criteria) this;
        }

        public Criteria andActiveBetween(Integer value1, Integer value2) {
            addCriterion("ACTIVE between", value1, value2, "active");
            return (Criteria) this;
        }

        public Criteria andActiveNotBetween(Integer value1, Integer value2) {
            addCriterion("ACTIVE not between", value1, value2, "active");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_building_area
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 06 17:06:31 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_building_area
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}