package vfh.httpInterface.model;

import java.util.Date;

public class Buildings {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings.id
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings.city_id
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    private Long cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings.area_id
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    private Long areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings.map_x
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    private String mapX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings.map_y
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    private String mapY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings.developer_company_id
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    private Long developerCompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings.bulidings_name
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    private String bulidingsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings.query_keyword
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    private String queryKeyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings.create_time
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings.update_time
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings.status
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings.open_date
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    private Date openDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings.deliver_date
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    private Date deliverDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings.server_phone_num
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    private String serverPhoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings.address
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings.id
     *
     * @return the value of tb_buildings.id
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings.id
     *
     * @param id the value for tb_buildings.id
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings.city_id
     *
     * @return the value of tb_buildings.city_id
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public Long getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings.city_id
     *
     * @param cityId the value for tb_buildings.city_id
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings.area_id
     *
     * @return the value of tb_buildings.area_id
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public Long getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings.area_id
     *
     * @param areaId the value for tb_buildings.area_id
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public void setAreaId(Long areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings.map_x
     *
     * @return the value of tb_buildings.map_x
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public String getMapX() {
        return mapX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings.map_x
     *
     * @param mapX the value for tb_buildings.map_x
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public void setMapX(String mapX) {
        this.mapX = mapX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings.map_y
     *
     * @return the value of tb_buildings.map_y
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public String getMapY() {
        return mapY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings.map_y
     *
     * @param mapY the value for tb_buildings.map_y
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public void setMapY(String mapY) {
        this.mapY = mapY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings.developer_company_id
     *
     * @return the value of tb_buildings.developer_company_id
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public Long getDeveloperCompanyId() {
        return developerCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings.developer_company_id
     *
     * @param developerCompanyId the value for tb_buildings.developer_company_id
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public void setDeveloperCompanyId(Long developerCompanyId) {
        this.developerCompanyId = developerCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings.bulidings_name
     *
     * @return the value of tb_buildings.bulidings_name
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public String getBulidingsName() {
        return bulidingsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings.bulidings_name
     *
     * @param bulidingsName the value for tb_buildings.bulidings_name
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public void setBulidingsName(String bulidingsName) {
        this.bulidingsName = bulidingsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings.query_keyword
     *
     * @return the value of tb_buildings.query_keyword
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public String getQueryKeyword() {
        return queryKeyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings.query_keyword
     *
     * @param queryKeyword the value for tb_buildings.query_keyword
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public void setQueryKeyword(String queryKeyword) {
        this.queryKeyword = queryKeyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings.create_time
     *
     * @return the value of tb_buildings.create_time
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings.create_time
     *
     * @param createTime the value for tb_buildings.create_time
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings.update_time
     *
     * @return the value of tb_buildings.update_time
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings.update_time
     *
     * @param updateTime the value for tb_buildings.update_time
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings.status
     *
     * @return the value of tb_buildings.status
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings.status
     *
     * @param status the value for tb_buildings.status
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings.open_date
     *
     * @return the value of tb_buildings.open_date
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public Date getOpenDate() {
        return openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings.open_date
     *
     * @param openDate the value for tb_buildings.open_date
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public void setOpenDate(Date openDate) {
        this.openDate = openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings.deliver_date
     *
     * @return the value of tb_buildings.deliver_date
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public Date getDeliverDate() {
        return deliverDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings.deliver_date
     *
     * @param deliverDate the value for tb_buildings.deliver_date
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public void setDeliverDate(Date deliverDate) {
        this.deliverDate = deliverDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings.server_phone_num
     *
     * @return the value of tb_buildings.server_phone_num
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public String getServerPhoneNum() {
        return serverPhoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings.server_phone_num
     *
     * @param serverPhoneNum the value for tb_buildings.server_phone_num
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public void setServerPhoneNum(String serverPhoneNum) {
        this.serverPhoneNum = serverPhoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings.address
     *
     * @return the value of tb_buildings.address
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings.address
     *
     * @param address the value for tb_buildings.address
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }
}