package vfh.httpInterface.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class BuildingsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public BuildingsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNull() {
            addCriterion("city_id is null");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNotNull() {
            addCriterion("city_id is not null");
            return (Criteria) this;
        }

        public Criteria andCityIdEqualTo(Long value) {
            addCriterion("city_id =", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotEqualTo(Long value) {
            addCriterion("city_id <>", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThan(Long value) {
            addCriterion("city_id >", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThanOrEqualTo(Long value) {
            addCriterion("city_id >=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThan(Long value) {
            addCriterion("city_id <", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThanOrEqualTo(Long value) {
            addCriterion("city_id <=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdIn(List<Long> values) {
            addCriterion("city_id in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotIn(List<Long> values) {
            addCriterion("city_id not in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdBetween(Long value1, Long value2) {
            addCriterion("city_id between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotBetween(Long value1, Long value2) {
            addCriterion("city_id not between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNull() {
            addCriterion("area_id is null");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNotNull() {
            addCriterion("area_id is not null");
            return (Criteria) this;
        }

        public Criteria andAreaIdEqualTo(Long value) {
            addCriterion("area_id =", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotEqualTo(Long value) {
            addCriterion("area_id <>", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThan(Long value) {
            addCriterion("area_id >", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThanOrEqualTo(Long value) {
            addCriterion("area_id >=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThan(Long value) {
            addCriterion("area_id <", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThanOrEqualTo(Long value) {
            addCriterion("area_id <=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIn(List<Long> values) {
            addCriterion("area_id in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotIn(List<Long> values) {
            addCriterion("area_id not in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdBetween(Long value1, Long value2) {
            addCriterion("area_id between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotBetween(Long value1, Long value2) {
            addCriterion("area_id not between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andMapXIsNull() {
            addCriterion("map_x is null");
            return (Criteria) this;
        }

        public Criteria andMapXIsNotNull() {
            addCriterion("map_x is not null");
            return (Criteria) this;
        }

        public Criteria andMapXEqualTo(String value) {
            addCriterion("map_x =", value, "mapX");
            return (Criteria) this;
        }

        public Criteria andMapXNotEqualTo(String value) {
            addCriterion("map_x <>", value, "mapX");
            return (Criteria) this;
        }

        public Criteria andMapXGreaterThan(String value) {
            addCriterion("map_x >", value, "mapX");
            return (Criteria) this;
        }

        public Criteria andMapXGreaterThanOrEqualTo(String value) {
            addCriterion("map_x >=", value, "mapX");
            return (Criteria) this;
        }

        public Criteria andMapXLessThan(String value) {
            addCriterion("map_x <", value, "mapX");
            return (Criteria) this;
        }

        public Criteria andMapXLessThanOrEqualTo(String value) {
            addCriterion("map_x <=", value, "mapX");
            return (Criteria) this;
        }

        public Criteria andMapXLike(String value) {
            addCriterion("map_x like", value, "mapX");
            return (Criteria) this;
        }

        public Criteria andMapXNotLike(String value) {
            addCriterion("map_x not like", value, "mapX");
            return (Criteria) this;
        }

        public Criteria andMapXIn(List<String> values) {
            addCriterion("map_x in", values, "mapX");
            return (Criteria) this;
        }

        public Criteria andMapXNotIn(List<String> values) {
            addCriterion("map_x not in", values, "mapX");
            return (Criteria) this;
        }

        public Criteria andMapXBetween(String value1, String value2) {
            addCriterion("map_x between", value1, value2, "mapX");
            return (Criteria) this;
        }

        public Criteria andMapXNotBetween(String value1, String value2) {
            addCriterion("map_x not between", value1, value2, "mapX");
            return (Criteria) this;
        }

        public Criteria andMapYIsNull() {
            addCriterion("map_y is null");
            return (Criteria) this;
        }

        public Criteria andMapYIsNotNull() {
            addCriterion("map_y is not null");
            return (Criteria) this;
        }

        public Criteria andMapYEqualTo(String value) {
            addCriterion("map_y =", value, "mapY");
            return (Criteria) this;
        }

        public Criteria andMapYNotEqualTo(String value) {
            addCriterion("map_y <>", value, "mapY");
            return (Criteria) this;
        }

        public Criteria andMapYGreaterThan(String value) {
            addCriterion("map_y >", value, "mapY");
            return (Criteria) this;
        }

        public Criteria andMapYGreaterThanOrEqualTo(String value) {
            addCriterion("map_y >=", value, "mapY");
            return (Criteria) this;
        }

        public Criteria andMapYLessThan(String value) {
            addCriterion("map_y <", value, "mapY");
            return (Criteria) this;
        }

        public Criteria andMapYLessThanOrEqualTo(String value) {
            addCriterion("map_y <=", value, "mapY");
            return (Criteria) this;
        }

        public Criteria andMapYLike(String value) {
            addCriterion("map_y like", value, "mapY");
            return (Criteria) this;
        }

        public Criteria andMapYNotLike(String value) {
            addCriterion("map_y not like", value, "mapY");
            return (Criteria) this;
        }

        public Criteria andMapYIn(List<String> values) {
            addCriterion("map_y in", values, "mapY");
            return (Criteria) this;
        }

        public Criteria andMapYNotIn(List<String> values) {
            addCriterion("map_y not in", values, "mapY");
            return (Criteria) this;
        }

        public Criteria andMapYBetween(String value1, String value2) {
            addCriterion("map_y between", value1, value2, "mapY");
            return (Criteria) this;
        }

        public Criteria andMapYNotBetween(String value1, String value2) {
            addCriterion("map_y not between", value1, value2, "mapY");
            return (Criteria) this;
        }

        public Criteria andDeveloperCompanyIdIsNull() {
            addCriterion("developer_company_id is null");
            return (Criteria) this;
        }

        public Criteria andDeveloperCompanyIdIsNotNull() {
            addCriterion("developer_company_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeveloperCompanyIdEqualTo(Long value) {
            addCriterion("developer_company_id =", value, "developerCompanyId");
            return (Criteria) this;
        }

        public Criteria andDeveloperCompanyIdNotEqualTo(Long value) {
            addCriterion("developer_company_id <>", value, "developerCompanyId");
            return (Criteria) this;
        }

        public Criteria andDeveloperCompanyIdGreaterThan(Long value) {
            addCriterion("developer_company_id >", value, "developerCompanyId");
            return (Criteria) this;
        }

        public Criteria andDeveloperCompanyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("developer_company_id >=", value, "developerCompanyId");
            return (Criteria) this;
        }

        public Criteria andDeveloperCompanyIdLessThan(Long value) {
            addCriterion("developer_company_id <", value, "developerCompanyId");
            return (Criteria) this;
        }

        public Criteria andDeveloperCompanyIdLessThanOrEqualTo(Long value) {
            addCriterion("developer_company_id <=", value, "developerCompanyId");
            return (Criteria) this;
        }

        public Criteria andDeveloperCompanyIdIn(List<Long> values) {
            addCriterion("developer_company_id in", values, "developerCompanyId");
            return (Criteria) this;
        }

        public Criteria andDeveloperCompanyIdNotIn(List<Long> values) {
            addCriterion("developer_company_id not in", values, "developerCompanyId");
            return (Criteria) this;
        }

        public Criteria andDeveloperCompanyIdBetween(Long value1, Long value2) {
            addCriterion("developer_company_id between", value1, value2, "developerCompanyId");
            return (Criteria) this;
        }

        public Criteria andDeveloperCompanyIdNotBetween(Long value1, Long value2) {
            addCriterion("developer_company_id not between", value1, value2, "developerCompanyId");
            return (Criteria) this;
        }

        public Criteria andBulidingsNameIsNull() {
            addCriterion("bulidings_name is null");
            return (Criteria) this;
        }

        public Criteria andBulidingsNameIsNotNull() {
            addCriterion("bulidings_name is not null");
            return (Criteria) this;
        }

        public Criteria andBulidingsNameEqualTo(String value) {
            addCriterion("bulidings_name =", value, "bulidingsName");
            return (Criteria) this;
        }

        public Criteria andBulidingsNameNotEqualTo(String value) {
            addCriterion("bulidings_name <>", value, "bulidingsName");
            return (Criteria) this;
        }

        public Criteria andBulidingsNameGreaterThan(String value) {
            addCriterion("bulidings_name >", value, "bulidingsName");
            return (Criteria) this;
        }

        public Criteria andBulidingsNameGreaterThanOrEqualTo(String value) {
            addCriterion("bulidings_name >=", value, "bulidingsName");
            return (Criteria) this;
        }

        public Criteria andBulidingsNameLessThan(String value) {
            addCriterion("bulidings_name <", value, "bulidingsName");
            return (Criteria) this;
        }

        public Criteria andBulidingsNameLessThanOrEqualTo(String value) {
            addCriterion("bulidings_name <=", value, "bulidingsName");
            return (Criteria) this;
        }

        public Criteria andBulidingsNameLike(String value) {
            addCriterion("bulidings_name like", value, "bulidingsName");
            return (Criteria) this;
        }

        public Criteria andBulidingsNameNotLike(String value) {
            addCriterion("bulidings_name not like", value, "bulidingsName");
            return (Criteria) this;
        }

        public Criteria andBulidingsNameIn(List<String> values) {
            addCriterion("bulidings_name in", values, "bulidingsName");
            return (Criteria) this;
        }

        public Criteria andBulidingsNameNotIn(List<String> values) {
            addCriterion("bulidings_name not in", values, "bulidingsName");
            return (Criteria) this;
        }

        public Criteria andBulidingsNameBetween(String value1, String value2) {
            addCriterion("bulidings_name between", value1, value2, "bulidingsName");
            return (Criteria) this;
        }

        public Criteria andBulidingsNameNotBetween(String value1, String value2) {
            addCriterion("bulidings_name not between", value1, value2, "bulidingsName");
            return (Criteria) this;
        }

        public Criteria andQueryKeywordIsNull() {
            addCriterion("query_keyword is null");
            return (Criteria) this;
        }

        public Criteria andQueryKeywordIsNotNull() {
            addCriterion("query_keyword is not null");
            return (Criteria) this;
        }

        public Criteria andQueryKeywordEqualTo(String value) {
            addCriterion("query_keyword =", value, "queryKeyword");
            return (Criteria) this;
        }

        public Criteria andQueryKeywordNotEqualTo(String value) {
            addCriterion("query_keyword <>", value, "queryKeyword");
            return (Criteria) this;
        }

        public Criteria andQueryKeywordGreaterThan(String value) {
            addCriterion("query_keyword >", value, "queryKeyword");
            return (Criteria) this;
        }

        public Criteria andQueryKeywordGreaterThanOrEqualTo(String value) {
            addCriterion("query_keyword >=", value, "queryKeyword");
            return (Criteria) this;
        }

        public Criteria andQueryKeywordLessThan(String value) {
            addCriterion("query_keyword <", value, "queryKeyword");
            return (Criteria) this;
        }

        public Criteria andQueryKeywordLessThanOrEqualTo(String value) {
            addCriterion("query_keyword <=", value, "queryKeyword");
            return (Criteria) this;
        }

        public Criteria andQueryKeywordLike(String value) {
            addCriterion("query_keyword like", value, "queryKeyword");
            return (Criteria) this;
        }

        public Criteria andQueryKeywordNotLike(String value) {
            addCriterion("query_keyword not like", value, "queryKeyword");
            return (Criteria) this;
        }

        public Criteria andQueryKeywordIn(List<String> values) {
            addCriterion("query_keyword in", values, "queryKeyword");
            return (Criteria) this;
        }

        public Criteria andQueryKeywordNotIn(List<String> values) {
            addCriterion("query_keyword not in", values, "queryKeyword");
            return (Criteria) this;
        }

        public Criteria andQueryKeywordBetween(String value1, String value2) {
            addCriterion("query_keyword between", value1, value2, "queryKeyword");
            return (Criteria) this;
        }

        public Criteria andQueryKeywordNotBetween(String value1, String value2) {
            addCriterion("query_keyword not between", value1, value2, "queryKeyword");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andOpenDateIsNull() {
            addCriterion("open_date is null");
            return (Criteria) this;
        }

        public Criteria andOpenDateIsNotNull() {
            addCriterion("open_date is not null");
            return (Criteria) this;
        }

        public Criteria andOpenDateEqualTo(Date value) {
            addCriterionForJDBCDate("open_date =", value, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("open_date <>", value, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateGreaterThan(Date value) {
            addCriterionForJDBCDate("open_date >", value, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("open_date >=", value, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateLessThan(Date value) {
            addCriterionForJDBCDate("open_date <", value, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("open_date <=", value, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateIn(List<Date> values) {
            addCriterionForJDBCDate("open_date in", values, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("open_date not in", values, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("open_date between", value1, value2, "openDate");
            return (Criteria) this;
        }

        public Criteria andOpenDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("open_date not between", value1, value2, "openDate");
            return (Criteria) this;
        }

        public Criteria andDeliverDateIsNull() {
            addCriterion("deliver_date is null");
            return (Criteria) this;
        }

        public Criteria andDeliverDateIsNotNull() {
            addCriterion("deliver_date is not null");
            return (Criteria) this;
        }

        public Criteria andDeliverDateEqualTo(Date value) {
            addCriterionForJDBCDate("deliver_date =", value, "deliverDate");
            return (Criteria) this;
        }

        public Criteria andDeliverDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("deliver_date <>", value, "deliverDate");
            return (Criteria) this;
        }

        public Criteria andDeliverDateGreaterThan(Date value) {
            addCriterionForJDBCDate("deliver_date >", value, "deliverDate");
            return (Criteria) this;
        }

        public Criteria andDeliverDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("deliver_date >=", value, "deliverDate");
            return (Criteria) this;
        }

        public Criteria andDeliverDateLessThan(Date value) {
            addCriterionForJDBCDate("deliver_date <", value, "deliverDate");
            return (Criteria) this;
        }

        public Criteria andDeliverDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("deliver_date <=", value, "deliverDate");
            return (Criteria) this;
        }

        public Criteria andDeliverDateIn(List<Date> values) {
            addCriterionForJDBCDate("deliver_date in", values, "deliverDate");
            return (Criteria) this;
        }

        public Criteria andDeliverDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("deliver_date not in", values, "deliverDate");
            return (Criteria) this;
        }

        public Criteria andDeliverDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("deliver_date between", value1, value2, "deliverDate");
            return (Criteria) this;
        }

        public Criteria andDeliverDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("deliver_date not between", value1, value2, "deliverDate");
            return (Criteria) this;
        }

        public Criteria andServerPhoneNumIsNull() {
            addCriterion("server_phone_num is null");
            return (Criteria) this;
        }

        public Criteria andServerPhoneNumIsNotNull() {
            addCriterion("server_phone_num is not null");
            return (Criteria) this;
        }

        public Criteria andServerPhoneNumEqualTo(String value) {
            addCriterion("server_phone_num =", value, "serverPhoneNum");
            return (Criteria) this;
        }

        public Criteria andServerPhoneNumNotEqualTo(String value) {
            addCriterion("server_phone_num <>", value, "serverPhoneNum");
            return (Criteria) this;
        }

        public Criteria andServerPhoneNumGreaterThan(String value) {
            addCriterion("server_phone_num >", value, "serverPhoneNum");
            return (Criteria) this;
        }

        public Criteria andServerPhoneNumGreaterThanOrEqualTo(String value) {
            addCriterion("server_phone_num >=", value, "serverPhoneNum");
            return (Criteria) this;
        }

        public Criteria andServerPhoneNumLessThan(String value) {
            addCriterion("server_phone_num <", value, "serverPhoneNum");
            return (Criteria) this;
        }

        public Criteria andServerPhoneNumLessThanOrEqualTo(String value) {
            addCriterion("server_phone_num <=", value, "serverPhoneNum");
            return (Criteria) this;
        }

        public Criteria andServerPhoneNumLike(String value) {
            addCriterion("server_phone_num like", value, "serverPhoneNum");
            return (Criteria) this;
        }

        public Criteria andServerPhoneNumNotLike(String value) {
            addCriterion("server_phone_num not like", value, "serverPhoneNum");
            return (Criteria) this;
        }

        public Criteria andServerPhoneNumIn(List<String> values) {
            addCriterion("server_phone_num in", values, "serverPhoneNum");
            return (Criteria) this;
        }

        public Criteria andServerPhoneNumNotIn(List<String> values) {
            addCriterion("server_phone_num not in", values, "serverPhoneNum");
            return (Criteria) this;
        }

        public Criteria andServerPhoneNumBetween(String value1, String value2) {
            addCriterion("server_phone_num between", value1, value2, "serverPhoneNum");
            return (Criteria) this;
        }

        public Criteria andServerPhoneNumNotBetween(String value1, String value2) {
            addCriterion("server_phone_num not between", value1, value2, "serverPhoneNum");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_buildings
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 06 17:03:44 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_buildings
     *
     * @mbggenerated Wed Jan 06 17:03:44 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}