package vfh.httpInterface.model;

public class BuildingsDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings_detail.id
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings_detail.building_count
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    private Integer buildingCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings_detail.floor_space
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    private Integer floorSpace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings_detail.building_space
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    private Integer buildingSpace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings_detail.house_count
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    private Integer houseCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings_detail.green_rate
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    private Integer greenRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings_detail.decoration_condition
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    private String decorationCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings_detail.util_type
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    private Integer utilType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_buildings_detail.parking_count
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    private Integer parkingCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings_detail.id
     *
     * @return the value of tb_buildings_detail.id
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings_detail.id
     *
     * @param id the value for tb_buildings_detail.id
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings_detail.building_count
     *
     * @return the value of tb_buildings_detail.building_count
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    public Integer getBuildingCount() {
        return buildingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings_detail.building_count
     *
     * @param buildingCount the value for tb_buildings_detail.building_count
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    public void setBuildingCount(Integer buildingCount) {
        this.buildingCount = buildingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings_detail.floor_space
     *
     * @return the value of tb_buildings_detail.floor_space
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    public Integer getFloorSpace() {
        return floorSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings_detail.floor_space
     *
     * @param floorSpace the value for tb_buildings_detail.floor_space
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    public void setFloorSpace(Integer floorSpace) {
        this.floorSpace = floorSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings_detail.building_space
     *
     * @return the value of tb_buildings_detail.building_space
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    public Integer getBuildingSpace() {
        return buildingSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings_detail.building_space
     *
     * @param buildingSpace the value for tb_buildings_detail.building_space
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    public void setBuildingSpace(Integer buildingSpace) {
        this.buildingSpace = buildingSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings_detail.house_count
     *
     * @return the value of tb_buildings_detail.house_count
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    public Integer getHouseCount() {
        return houseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings_detail.house_count
     *
     * @param houseCount the value for tb_buildings_detail.house_count
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    public void setHouseCount(Integer houseCount) {
        this.houseCount = houseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings_detail.green_rate
     *
     * @return the value of tb_buildings_detail.green_rate
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    public Integer getGreenRate() {
        return greenRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings_detail.green_rate
     *
     * @param greenRate the value for tb_buildings_detail.green_rate
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    public void setGreenRate(Integer greenRate) {
        this.greenRate = greenRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings_detail.decoration_condition
     *
     * @return the value of tb_buildings_detail.decoration_condition
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    public String getDecorationCondition() {
        return decorationCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings_detail.decoration_condition
     *
     * @param decorationCondition the value for tb_buildings_detail.decoration_condition
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    public void setDecorationCondition(String decorationCondition) {
        this.decorationCondition = decorationCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings_detail.util_type
     *
     * @return the value of tb_buildings_detail.util_type
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    public Integer getUtilType() {
        return utilType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings_detail.util_type
     *
     * @param utilType the value for tb_buildings_detail.util_type
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    public void setUtilType(Integer utilType) {
        this.utilType = utilType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_buildings_detail.parking_count
     *
     * @return the value of tb_buildings_detail.parking_count
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    public Integer getParkingCount() {
        return parkingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_buildings_detail.parking_count
     *
     * @param parkingCount the value for tb_buildings_detail.parking_count
     *
     * @mbggenerated Wed Jan 06 17:08:26 CST 2016
     */
    public void setParkingCount(Integer parkingCount) {
        this.parkingCount = parkingCount;
    }
}