package vfh.httpInterface.model;

import java.util.Date;

public class BuildingsPrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_price.id
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_price.nomal_price
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    private Double nomalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_price.discount_price
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    private Double discountPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_price.active_id
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    private Long activeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_price.building_id
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    private Long buildingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_price.start_date
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_price.end_date
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_price.create_time
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_price.update_time
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_price.id
     *
     * @return the value of tb_building_price.id
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_price.id
     *
     * @param id the value for tb_building_price.id
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_price.nomal_price
     *
     * @return the value of tb_building_price.nomal_price
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    public Double getNomalPrice() {
        return nomalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_price.nomal_price
     *
     * @param nomalPrice the value for tb_building_price.nomal_price
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    public void setNomalPrice(Double nomalPrice) {
        this.nomalPrice = nomalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_price.discount_price
     *
     * @return the value of tb_building_price.discount_price
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    public Double getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_price.discount_price
     *
     * @param discountPrice the value for tb_building_price.discount_price
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    public void setDiscountPrice(Double discountPrice) {
        this.discountPrice = discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_price.active_id
     *
     * @return the value of tb_building_price.active_id
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    public Long getActiveId() {
        return activeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_price.active_id
     *
     * @param activeId the value for tb_building_price.active_id
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    public void setActiveId(Long activeId) {
        this.activeId = activeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_price.building_id
     *
     * @return the value of tb_building_price.building_id
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    public Long getBuildingId() {
        return buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_price.building_id
     *
     * @param buildingId the value for tb_building_price.building_id
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    public void setBuildingId(Long buildingId) {
        this.buildingId = buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_price.start_date
     *
     * @return the value of tb_building_price.start_date
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_price.start_date
     *
     * @param startDate the value for tb_building_price.start_date
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_price.end_date
     *
     * @return the value of tb_building_price.end_date
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_price.end_date
     *
     * @param endDate the value for tb_building_price.end_date
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_price.create_time
     *
     * @return the value of tb_building_price.create_time
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_price.create_time
     *
     * @param createTime the value for tb_building_price.create_time
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_price.update_time
     *
     * @return the value of tb_building_price.update_time
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_price.update_time
     *
     * @param updateTime the value for tb_building_price.update_time
     *
     * @mbggenerated Wed Jan 06 17:10:43 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}