package vfh.httpInterface.model;

public class BuildingArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.AREA_ID
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private String areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.AREA_NAME
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.AREA_ALIA
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private String areaAlia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.PARENT_AREA_ID
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private String parentAreaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.PRO_ID
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private String proId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.PRO_NAME
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private String proName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.PRO_ALIA
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private String proAlia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.CITY_ID
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private String cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.CITY_NAME
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.CITY_ALIA
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private String cityAlia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.AREA_LEVEL
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private String areaLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.POST_CODE
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.TEL_AREA_NO
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private String telAreaNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.AREA
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.ORDER_ID
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.LATITUDE
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.LONGITUDE
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.SPELL
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private String spell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.SHORT_SPELL
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private String shortSpell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.AREA_CLUSTER
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private String areaCluster;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.APP_PREVENT
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private String appPrevent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.SEARCH_TYPE
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private String searchType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.INSTALLED
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private Integer installed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.ACTIVATION
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private Integer activation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_area.ACTIVE
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    private Integer active;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.AREA_ID
     *
     * @return the value of tb_building_area.AREA_ID
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.AREA_ID
     *
     * @param areaId the value for tb_building_area.AREA_ID
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.AREA_NAME
     *
     * @return the value of tb_building_area.AREA_NAME
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.AREA_NAME
     *
     * @param areaName the value for tb_building_area.AREA_NAME
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.AREA_ALIA
     *
     * @return the value of tb_building_area.AREA_ALIA
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getAreaAlia() {
        return areaAlia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.AREA_ALIA
     *
     * @param areaAlia the value for tb_building_area.AREA_ALIA
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setAreaAlia(String areaAlia) {
        this.areaAlia = areaAlia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.PARENT_AREA_ID
     *
     * @return the value of tb_building_area.PARENT_AREA_ID
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getParentAreaId() {
        return parentAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.PARENT_AREA_ID
     *
     * @param parentAreaId the value for tb_building_area.PARENT_AREA_ID
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setParentAreaId(String parentAreaId) {
        this.parentAreaId = parentAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.PRO_ID
     *
     * @return the value of tb_building_area.PRO_ID
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.PRO_ID
     *
     * @param proId the value for tb_building_area.PRO_ID
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setProId(String proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.PRO_NAME
     *
     * @return the value of tb_building_area.PRO_NAME
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.PRO_NAME
     *
     * @param proName the value for tb_building_area.PRO_NAME
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setProName(String proName) {
        this.proName = proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.PRO_ALIA
     *
     * @return the value of tb_building_area.PRO_ALIA
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getProAlia() {
        return proAlia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.PRO_ALIA
     *
     * @param proAlia the value for tb_building_area.PRO_ALIA
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setProAlia(String proAlia) {
        this.proAlia = proAlia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.CITY_ID
     *
     * @return the value of tb_building_area.CITY_ID
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.CITY_ID
     *
     * @param cityId the value for tb_building_area.CITY_ID
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setCityId(String cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.CITY_NAME
     *
     * @return the value of tb_building_area.CITY_NAME
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.CITY_NAME
     *
     * @param cityName the value for tb_building_area.CITY_NAME
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.CITY_ALIA
     *
     * @return the value of tb_building_area.CITY_ALIA
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getCityAlia() {
        return cityAlia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.CITY_ALIA
     *
     * @param cityAlia the value for tb_building_area.CITY_ALIA
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setCityAlia(String cityAlia) {
        this.cityAlia = cityAlia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.AREA_LEVEL
     *
     * @return the value of tb_building_area.AREA_LEVEL
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getAreaLevel() {
        return areaLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.AREA_LEVEL
     *
     * @param areaLevel the value for tb_building_area.AREA_LEVEL
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setAreaLevel(String areaLevel) {
        this.areaLevel = areaLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.POST_CODE
     *
     * @return the value of tb_building_area.POST_CODE
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.POST_CODE
     *
     * @param postCode the value for tb_building_area.POST_CODE
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.TEL_AREA_NO
     *
     * @return the value of tb_building_area.TEL_AREA_NO
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getTelAreaNo() {
        return telAreaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.TEL_AREA_NO
     *
     * @param telAreaNo the value for tb_building_area.TEL_AREA_NO
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setTelAreaNo(String telAreaNo) {
        this.telAreaNo = telAreaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.AREA
     *
     * @return the value of tb_building_area.AREA
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.AREA
     *
     * @param area the value for tb_building_area.AREA
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.ORDER_ID
     *
     * @return the value of tb_building_area.ORDER_ID
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.ORDER_ID
     *
     * @param orderId the value for tb_building_area.ORDER_ID
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.LATITUDE
     *
     * @return the value of tb_building_area.LATITUDE
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.LATITUDE
     *
     * @param latitude the value for tb_building_area.LATITUDE
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.LONGITUDE
     *
     * @return the value of tb_building_area.LONGITUDE
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.LONGITUDE
     *
     * @param longitude the value for tb_building_area.LONGITUDE
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.SPELL
     *
     * @return the value of tb_building_area.SPELL
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getSpell() {
        return spell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.SPELL
     *
     * @param spell the value for tb_building_area.SPELL
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setSpell(String spell) {
        this.spell = spell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.SHORT_SPELL
     *
     * @return the value of tb_building_area.SHORT_SPELL
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getShortSpell() {
        return shortSpell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.SHORT_SPELL
     *
     * @param shortSpell the value for tb_building_area.SHORT_SPELL
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setShortSpell(String shortSpell) {
        this.shortSpell = shortSpell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.AREA_CLUSTER
     *
     * @return the value of tb_building_area.AREA_CLUSTER
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getAreaCluster() {
        return areaCluster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.AREA_CLUSTER
     *
     * @param areaCluster the value for tb_building_area.AREA_CLUSTER
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setAreaCluster(String areaCluster) {
        this.areaCluster = areaCluster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.APP_PREVENT
     *
     * @return the value of tb_building_area.APP_PREVENT
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getAppPrevent() {
        return appPrevent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.APP_PREVENT
     *
     * @param appPrevent the value for tb_building_area.APP_PREVENT
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setAppPrevent(String appPrevent) {
        this.appPrevent = appPrevent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.SEARCH_TYPE
     *
     * @return the value of tb_building_area.SEARCH_TYPE
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public String getSearchType() {
        return searchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.SEARCH_TYPE
     *
     * @param searchType the value for tb_building_area.SEARCH_TYPE
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setSearchType(String searchType) {
        this.searchType = searchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.INSTALLED
     *
     * @return the value of tb_building_area.INSTALLED
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public Integer getInstalled() {
        return installed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.INSTALLED
     *
     * @param installed the value for tb_building_area.INSTALLED
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setInstalled(Integer installed) {
        this.installed = installed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.ACTIVATION
     *
     * @return the value of tb_building_area.ACTIVATION
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public Integer getActivation() {
        return activation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.ACTIVATION
     *
     * @param activation the value for tb_building_area.ACTIVATION
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setActivation(Integer activation) {
        this.activation = activation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_area.ACTIVE
     *
     * @return the value of tb_building_area.ACTIVE
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public Integer getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_area.ACTIVE
     *
     * @param active the value for tb_building_area.ACTIVE
     *
     * @mbggenerated Wed Jan 06 17:06:31 CST 2016
     */
    public void setActive(Integer active) {
        this.active = active;
    }
}