package vfh.httpInterface.model;

import java.util.Date;

public class BuildingsResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_resource.id
     *
     * @mbggenerated Wed Jan 06 17:12:02 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_resource.resource_path
     *
     * @mbggenerated Wed Jan 06 17:12:02 CST 2016
     */
    private String resourcePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_resource.resource_name
     *
     * @mbggenerated Wed Jan 06 17:12:02 CST 2016
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_resource.resource_alias
     *
     * @mbggenerated Wed Jan 06 17:12:02 CST 2016
     */
    private String resourceAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_resource.create_time
     *
     * @mbggenerated Wed Jan 06 17:12:02 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_resource.update_time
     *
     * @mbggenerated Wed Jan 06 17:12:02 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_resource.resource_detail
     *
     * @mbggenerated Wed Jan 06 17:12:02 CST 2016
     */
    private String resourceDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_resource.id
     *
     * @return the value of tb_building_resource.id
     *
     * @mbggenerated Wed Jan 06 17:12:02 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_resource.id
     *
     * @param id the value for tb_building_resource.id
     *
     * @mbggenerated Wed Jan 06 17:12:02 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_resource.resource_path
     *
     * @return the value of tb_building_resource.resource_path
     *
     * @mbggenerated Wed Jan 06 17:12:02 CST 2016
     */
    public String getResourcePath() {
        return resourcePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_resource.resource_path
     *
     * @param resourcePath the value for tb_building_resource.resource_path
     *
     * @mbggenerated Wed Jan 06 17:12:02 CST 2016
     */
    public void setResourcePath(String resourcePath) {
        this.resourcePath = resourcePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_resource.resource_name
     *
     * @return the value of tb_building_resource.resource_name
     *
     * @mbggenerated Wed Jan 06 17:12:02 CST 2016
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_resource.resource_name
     *
     * @param resourceName the value for tb_building_resource.resource_name
     *
     * @mbggenerated Wed Jan 06 17:12:02 CST 2016
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_resource.resource_alias
     *
     * @return the value of tb_building_resource.resource_alias
     *
     * @mbggenerated Wed Jan 06 17:12:02 CST 2016
     */
    public String getResourceAlias() {
        return resourceAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_resource.resource_alias
     *
     * @param resourceAlias the value for tb_building_resource.resource_alias
     *
     * @mbggenerated Wed Jan 06 17:12:02 CST 2016
     */
    public void setResourceAlias(String resourceAlias) {
        this.resourceAlias = resourceAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_resource.create_time
     *
     * @return the value of tb_building_resource.create_time
     *
     * @mbggenerated Wed Jan 06 17:12:02 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_resource.create_time
     *
     * @param createTime the value for tb_building_resource.create_time
     *
     * @mbggenerated Wed Jan 06 17:12:02 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_resource.update_time
     *
     * @return the value of tb_building_resource.update_time
     *
     * @mbggenerated Wed Jan 06 17:12:02 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_resource.update_time
     *
     * @param updateTime the value for tb_building_resource.update_time
     *
     * @mbggenerated Wed Jan 06 17:12:02 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_resource.resource_detail
     *
     * @return the value of tb_building_resource.resource_detail
     *
     * @mbggenerated Wed Jan 06 17:12:02 CST 2016
     */
    public String getResourceDetail() {
        return resourceDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_resource.resource_detail
     *
     * @param resourceDetail the value for tb_building_resource.resource_detail
     *
     * @mbggenerated Wed Jan 06 17:12:02 CST 2016
     */
    public void setResourceDetail(String resourceDetail) {
        this.resourceDetail = resourceDetail;
    }
}