package vfh.httpInterface.model;

import java.util.Date;

public class BuildingActive {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_active.id
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_active.active_name
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    private String activeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_active.active_type
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    private Integer activeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_active.start_date
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_active.end_date
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_active.create_time
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_active.update_time
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_active.active_price
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    private Double activePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_active.active_detail
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    private String activeDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_active.id
     *
     * @return the value of tb_building_active.id
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_active.id
     *
     * @param id the value for tb_building_active.id
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_active.active_name
     *
     * @return the value of tb_building_active.active_name
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    public String getActiveName() {
        return activeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_active.active_name
     *
     * @param activeName the value for tb_building_active.active_name
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    public void setActiveName(String activeName) {
        this.activeName = activeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_active.active_type
     *
     * @return the value of tb_building_active.active_type
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    public Integer getActiveType() {
        return activeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_active.active_type
     *
     * @param activeType the value for tb_building_active.active_type
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    public void setActiveType(Integer activeType) {
        this.activeType = activeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_active.start_date
     *
     * @return the value of tb_building_active.start_date
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_active.start_date
     *
     * @param startDate the value for tb_building_active.start_date
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_active.end_date
     *
     * @return the value of tb_building_active.end_date
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_active.end_date
     *
     * @param endDate the value for tb_building_active.end_date
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_active.create_time
     *
     * @return the value of tb_building_active.create_time
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_active.create_time
     *
     * @param createTime the value for tb_building_active.create_time
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_active.update_time
     *
     * @return the value of tb_building_active.update_time
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_active.update_time
     *
     * @param updateTime the value for tb_building_active.update_time
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_active.active_price
     *
     * @return the value of tb_building_active.active_price
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    public Double getActivePrice() {
        return activePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_active.active_price
     *
     * @param activePrice the value for tb_building_active.active_price
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    public void setActivePrice(Double activePrice) {
        this.activePrice = activePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_active.active_detail
     *
     * @return the value of tb_building_active.active_detail
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    public String getActiveDetail() {
        return activeDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_active.active_detail
     *
     * @param activeDetail the value for tb_building_active.active_detail
     *
     * @mbggenerated Wed Jan 06 17:05:46 CST 2016
     */
    public void setActiveDetail(String activeDetail) {
        this.activeDetail = activeDetail;
    }
}