package vfh.httpInterface.model;

import java.util.Date;

public class BuildingCompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_company.id
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_company.company_name
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_company.pre_company_id
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    private Long preCompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_company.business_entity
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    private String businessEntity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_company.city_id
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    private Long cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_company.area_id
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    private Long areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_company.address
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_company.create_time
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_company.update_time
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_company.id
     *
     * @return the value of tb_building_company.id
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_company.id
     *
     * @param id the value for tb_building_company.id
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_company.company_name
     *
     * @return the value of tb_building_company.company_name
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_company.company_name
     *
     * @param companyName the value for tb_building_company.company_name
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_company.pre_company_id
     *
     * @return the value of tb_building_company.pre_company_id
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    public Long getPreCompanyId() {
        return preCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_company.pre_company_id
     *
     * @param preCompanyId the value for tb_building_company.pre_company_id
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    public void setPreCompanyId(Long preCompanyId) {
        this.preCompanyId = preCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_company.business_entity
     *
     * @return the value of tb_building_company.business_entity
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    public String getBusinessEntity() {
        return businessEntity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_company.business_entity
     *
     * @param businessEntity the value for tb_building_company.business_entity
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    public void setBusinessEntity(String businessEntity) {
        this.businessEntity = businessEntity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_company.city_id
     *
     * @return the value of tb_building_company.city_id
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    public Long getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_company.city_id
     *
     * @param cityId the value for tb_building_company.city_id
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_company.area_id
     *
     * @return the value of tb_building_company.area_id
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    public Long getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_company.area_id
     *
     * @param areaId the value for tb_building_company.area_id
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    public void setAreaId(Long areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_company.address
     *
     * @return the value of tb_building_company.address
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_company.address
     *
     * @param address the value for tb_building_company.address
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_company.create_time
     *
     * @return the value of tb_building_company.create_time
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_company.create_time
     *
     * @param createTime the value for tb_building_company.create_time
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_company.update_time
     *
     * @return the value of tb_building_company.update_time
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_company.update_time
     *
     * @param updateTime the value for tb_building_company.update_time
     *
     * @mbggenerated Wed Jan 06 17:07:25 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}