package vfh.httpInterface.model;

import java.util.Date;

public class BuildingsHouseType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_house_type.id
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_house_type.house_type
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    private Integer houseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_house_type.acreage
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    private Integer acreage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_house_type.building_id
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    private Long buildingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_house_type.create_time
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_house_type.update_time
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_house_type.id
     *
     * @return the value of tb_building_house_type.id
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_house_type.id
     *
     * @param id the value for tb_building_house_type.id
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_house_type.house_type
     *
     * @return the value of tb_building_house_type.house_type
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    public Integer getHouseType() {
        return houseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_house_type.house_type
     *
     * @param houseType the value for tb_building_house_type.house_type
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    public void setHouseType(Integer houseType) {
        this.houseType = houseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_house_type.acreage
     *
     * @return the value of tb_building_house_type.acreage
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    public Integer getAcreage() {
        return acreage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_house_type.acreage
     *
     * @param acreage the value for tb_building_house_type.acreage
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    public void setAcreage(Integer acreage) {
        this.acreage = acreage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_house_type.building_id
     *
     * @return the value of tb_building_house_type.building_id
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    public Long getBuildingId() {
        return buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_house_type.building_id
     *
     * @param buildingId the value for tb_building_house_type.building_id
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    public void setBuildingId(Long buildingId) {
        this.buildingId = buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_house_type.create_time
     *
     * @return the value of tb_building_house_type.create_time
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_house_type.create_time
     *
     * @param createTime the value for tb_building_house_type.create_time
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_house_type.update_time
     *
     * @return the value of tb_building_house_type.update_time
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_house_type.update_time
     *
     * @param updateTime the value for tb_building_house_type.update_time
     *
     * @mbggenerated Wed Jan 06 17:09:51 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}