package vfh.httpInterface.model;

import java.util.Date;

public class BuildingKeyValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_key_value.id
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_key_value.table_name
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_key_value.field_name
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    private String fieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_key_value.key
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_key_value.value
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_key_value.create_time
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_building_key_value.update_time
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_key_value.id
     *
     * @return the value of tb_building_key_value.id
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_key_value.id
     *
     * @param id the value for tb_building_key_value.id
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_key_value.table_name
     *
     * @return the value of tb_building_key_value.table_name
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_key_value.table_name
     *
     * @param tableName the value for tb_building_key_value.table_name
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_key_value.field_name
     *
     * @return the value of tb_building_key_value.field_name
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_key_value.field_name
     *
     * @param fieldName the value for tb_building_key_value.field_name
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_key_value.key
     *
     * @return the value of tb_building_key_value.key
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_key_value.key
     *
     * @param key the value for tb_building_key_value.key
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_key_value.value
     *
     * @return the value of tb_building_key_value.value
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_key_value.value
     *
     * @param value the value for tb_building_key_value.value
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_key_value.create_time
     *
     * @return the value of tb_building_key_value.create_time
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_key_value.create_time
     *
     * @param createTime the value for tb_building_key_value.create_time
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_building_key_value.update_time
     *
     * @return the value of tb_building_key_value.update_time
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_building_key_value.update_time
     *
     * @param updateTime the value for tb_building_key_value.update_time
     *
     * @mbggenerated Wed Jan 06 17:07:56 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}